### ISSUE TITLE
数据集下载

### ISSUE THREAD

**Issue by DrugD** [akira-l/VrR-VG#1]
问一下，这个数据集在哪下呢

**Comment by MinglangQiao** [comment]
这里可以下载：http://vrrvg.com/#04

**Comment by CharlieLei** [comment]
> 这里可以下载：http://vrrvg.com/#04

这个链接失效了，能重新补一下吗

**Comment by akira-l** [comment]
https://drive.google.com/open?id=15i5J87FHfZ1DwPkumBaH50nfOg01Ja8C

**Comment by akira-l** [comment]
感谢关注我们的工作，网站之前DNS挂了，刚给重新更新了。

**Comment by zhuyibing** [comment]
大家知这个对应的VG150在哪里下载吗

**Comment by akira-l** [comment]
VG150就是常规的scene graph benchmark
